### ISSUE TITLE
On wide screens the text fills up the horizontal space - UI improvement

### ISSUE THREAD

**Issue by roberttorfason** [embernet/sidekick#17]
In ChatGPT and on websites in general, text is usually wrapped into a limited size. This is done because it's much easier to read (and probably other reasons as well).

Currently sidekick fills in the horizontal space which makes the output hard to read, especially on wide screens

SIdekick doesn't wrap:
![image](https://github.com/embernet/sidekick/assets/8184865/ae8afc2f-654b-4a45-9031-cfe2bf8f4380)

ChatGPT wraps:
![image](https://github.com/embernet/sidekick/assets/8184865/c493e586-240c-436b-8435-bc99c54aa61f)

**Comment by embernet** [comment]
Good point, will set a max width for all panels in r0.0.8.
