### ISSUE TITLE
Personas that provide concise answers missing

### ISSUE THREAD

**Issue by roberttorfason** [embernet/sidekick#19]
In ChatGPT there is a system prompt. A very common one goes along the lines of "be concise, get directly to the answer, don't apologize". There is a persona like this missing.

On that note, the default persona "the answerer" is quite frustrating because it provides incredibly lengthy answers to simple queries, even when adding "be concise" to the prompt (probably hard to overwrite the original prompt). We should probably have a discussion on what the default persona should be.

**Comment by embernet** [comment]
Nice idea: Adding a concise persona to 0.0.8. Bullet man does do this already but also makes the output a bullet list, it makes sense to have one that is text based.

There is a None persona that I am renaming neutral, and making it the default - this results in no persona - just using the base model response.

Re the UI addition for having a few main personas, this is already in there - click the heart on a persona to add or remove it from your favourites list and click the heart next to the filter to only show favourites.

**Comment by roberttorfason** [comment]
Yes, didn't realise the favourites and hadn't seen "None" persona. That's very useful, thanks!
