### ISSUE TITLE
Clicking persona above the chat box multiple times in a row opens different panels

### ISSUE THREAD

**Issue by roberttorfason** [embernet/sidekick#2]
How to reproduce:

Click the "Advisor" multiple time and sometimes "settings" open and sometimes advisor

**Comment by embernet** [comment]
Odd one, can't reproduce this. If you can maybe you can show me tomorrow.

**Comment by roberttorfason** [comment]
I just realized this isn't a bug. I thought "Bullet man (Creative)" was a single unit so I was clicking (Creative) expecting it to open personas. I guess I was also confused by the fact that clicking Creative opens settings since I didn't realize it was there.

```
Bullet man (Creative)  gpt4
```

I think we could add some sort of separating between the three words, boxes or some delimiters to highlight these are different things. Some version of:

```
Bullet man - Creative - Gpt4
```

**Comment by embernet** [comment]
Fixed this in 0.0.6 by making them buttons so the separation is clear.
