### ISSUE TITLE
When logging in, everything is empty 

### ISSUE THREAD

**Issue by roberttorfason** [embernet/sidekick#22]
A user needs to click the "new chat" icon to get the chat open. Should probably default to having the chat open. Especially for users that are trying it out for the first time

![image](https://github.com/embernet/sidekick/assets/8184865/7c909dd3-016f-4dc6-9ce8-9753be0319ca)

**Comment by embernet** [comment]
Default now is for a new user the first time the app opens it shows the help, chats, and chat panels. For subsequent logins it shows whichever panels the user has open last time.
