### ISSUE TITLE
Add a "No persona" persona

### ISSUE THREAD

**Issue by roberttorfason** [embernet/sidekick#3]
Sometimes a user just wants the "standard" answer from the LLM

**Comment by embernet** [comment]
Thanks, makes sense, do you think this perhaps should even be the default persona?

**Comment by roberttorfason** [comment]
In my opinion it should be, and then allow a user to easily change the default. Also you could view OpenAI default is some sort of persona, it has a big prompt somewhere behind the scenes

**Comment by embernet** [comment]
in r0.0.8
